### ISSUE TITLE
NullPointerException on acquireLocation()

### ISSUE THREAD

**Issue by andrelramos** [klaasnotfound/LocationAssistant#2]
On my application i caught the exception below in a tablet OneTouch EVO7

```jsx
Fatal Exception: java.lang.NullPointerException
       at com.example.LocationAssistant.checkLocationAvailability(LocationAssistant.java:508)
       at com.example.LocationAssistant.acquireLocation(LocationAssistant.java:450)
       at com.example.LocationAssistant$1.run(LocationAssistant.java:444)
```

I fixed it using a try/catch statement, but a don't it know if is the best solution

**Comment by klaasnotfound** [comment]
Hey @andrelramos, thanks for pointing this out and sorry it took me a while to get around to it. I was relying on a result from the Location API that [may actually be null](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi#getLocationAvailability(com.google.android.gms.common.api.GoogleApiClient)), which is what caused the NPE. Try/catch is not the best way, I'm pushing a fix in a second.
